POST http://localhost:8082/users
Content-Type: application/json

{
  "name": "User name",
  "email": "test@email.com",
  "password": "testpassword"
}

###

POST http://localhost:8082/users/generate_token
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "testpassword"
}

###

GET http://localhost:8082/users/test@email.com
Content-Type: application/json